# =========================
# APPLICATION
# =========================
spring.application.name=zvrms


# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://ep-bitter-brook-a4zccnbq-pooler.us-east-1.aws.neon.tech/mamahealth?sslmode=require
spring.datasource.username=default
spring.datasource.password=xUVs0Qyk8LZC
spring.datasource.driver-class-name=org.postgresql.Driver


# Local Database 
# spring.datasource.url=jdbc:postgresql://localhost:5432/zvrms
# spring.datasource.username=salma
# spring.datasource.password=salma123
# spring.datasource.driver-class-name=org.postgresql.Driver

# Auto-updates database schema if needed
spring.jpa.hibernate.ddl-auto=update

# =========================
# JPA
# =========================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# JWT
# =========================
jwt.secret=ZVRMSSecretKey2026ForJWTAuthenticationSystemVerySecure123456789
jwt.expiration=86400000

# =========================
# FILE UPLOAD
# =========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =========================
# LOGGING
# =========================
logging.level.org.springframework.security=DEBUG